### ISSUE TITLE
Links from Packt course to GitHub are broken

### ISSUE THREAD

**Issue by Fringilla** [PacktPublishing/learn-sql-database-programming#1]
For example in: https://subscription.packtpub.com/book/data/9781838984762/5/ch05lvl1sec26/technical-requirements it states

The code files of this chapter can be found at https://github.com/PacktPublishing/learn-sql-database-programming/tree/master/chapter-4.

which should be now https://github.com/PacktPublishing/learn-sql-database-programming/tree/master/Chapter04

![afbeelding](https://user-images.githubusercontent.com/3116230/85945540-dc19a300-b93e-11ea-8bb5-8dc3f21c2606.png)

**Comment by packt-pradeeps** [comment]
Hello @Fringilla ,

We've renamed the folders on GitHub to match with the course link. Now the links mentioned in the book works perfectly fine. Hope this solves your issue and thanks for bringing this to our notice.

Best Regards,
Packt Team
